version: '3.8'

services:
  ffc-ahwr-notification:
    build:
      context: .
      target: production
    image: ffc-ahwr-notification
    container_name: ffc-ahwr-notification
    environment:
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-notset}
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      NOTIFY_SUBMITTED_SUBSCRIPTION_ADDRESS: ${NOTIFY_SUBMITTED_SUBSCRIPTION_ADDRESS:-notset}
      NOTIFY_SUBMITTED_TOPIC_ADDRESS: ${NOTIFY_SUBMITTED_TOPIC_ADDRESS:-notset}
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-notification
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY:-notset}
