version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-notification:
    build:
      target: development
    image: ffc-ahwr-notification-development
    container_name: ffc-ahwr-notification-development
    ports:
      - "3004:3000"
      - "9233:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
