{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-notification.container-secret") -}}
{{- define "ffc-ahwr-notification.container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
{{- end -}}