environment: development
name: ffc-ahwr-notification
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-notification

labels: {}

appInsights:
  key: not-a-real-key

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-ahwr-notification-config-map

containerSecret:
  name: ffc-ahwr-notification-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  replicas: 2
  minReplicas: 2
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  notifyApiKey: dummy-helm-value
  messageQueueHost: dummy
  notifySubmittedTopicAddress: notify-submitted
  notifySubmittedSubscriptionAddress: notify-notification
  protectiveMonitoringUrl:

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
